# Generated by Django 3.2.12 on 2022-03-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_book_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='dbebook',
            field=models.FileField(null=True, upload_to='dbebook/'),
        ),
    ]
